---
title: "Selected Publications"
---


* Lester, S. E., Dubel, A.K., Hernan, G., **McHenry, J.**, & A. Rassweiler. Applying spatial planning principles to marine ecosystem restoration. Frontiers in Marine Science. 2020.



* **McHenry, J.**, Welch H., Lester S.E., & V. Saba. Projecting marine species range shifts from ocean temperatures masks climate vulnerability. Global Change Biology. 2019.



* Siegel, K. J., Cabral, R. B., **McHenry, J.**, Ojea, E., Owashi, B., & S.E. Lester, S. E. Sovereign states in the Caribbean have lower social-ecological vulnerability to coral bleaching than overseas territories. Proceedings of the Royal Society B. 2019. 



* Welch H, & **J. McHenry**. Planning for dynamic process: An assemblage‐level surrogate strategy for species seasonal movement pathways. Aquatic Conservation: Marine and Freshwater Ecosystems. 2018.   



* Lester, S. E., E.O. Ruff, K. Mayall, **J. McHenry**. Exploring stakeholder perceptions of marine management in Bermuda. Marine. Policy. 2017  




* **McHenry, J.**, R.S. Steneck, & D.C. Brady. Abiotic proxies for predictive mapping of near‐shore benthic assemblages: Implications for marine spatial planning. Ecological Applications. 2017.   



For a full list of my publications see my [**Google Scholar**](https://scholar.google.com/citations?user=NQ2HpooAAAAJ&hl=en) and [**ResearchGate**](https://www.researchgate.net/profile/Jennifer_Mchenry3) pages. If any are inaccessible online, feel free to contact me about PDFs versions of my publications.



